ProjetoDHZMilhos/Models/EspecieMilho/CategoriaMilho.cs
namespace ProjetoDHZMilhos.Models.EspecieMilho
{
    public enum CategoriaMilho
    {
        Dentado = 0,
        Doce = 1,
        Duro = 2,
        Mole = 3,
        Pipoca = 4
    }

}

ProjetoDHZMilhos/Models/EspecieMilho/EspecieMilhoModel.cs
namespace ProjetoDHZMilhos.Models.EspecieMilho
{
    public class EspecieMilhoModel
    {
        public int ID { get; set; }
        public string Nome { get; set; }
        public CategoriaMilho Categoria { get; set; }
        public string CorExterna { get; set; }
        public int RendimentoIndustrial { get; set; }
        public string UniformidadeColheita { get; set; }
        public string EstacaoTransplante { get; set; }
        public string EstacaoPlantio { get; set; }
        public string EstacaoColheita { get; set; }
        public bool Biotech { get; set; }
    }
}

ProjetoDHZMilhos/Models/EspecieMilho/EspeciesMilhoModel.cs
namespace ProjetoDHZMilhos.Models.EspecieMilho
{
    public class EspeciesMilhoModel
    {
        public List<EspecieMilhoModel> EspeciesMilho { get; set; }
    }
}

ProjetoDHZMilhos/Controllers/EspecieMilhoController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoDHZMilhos.Models.EspecieMilho;

namespace ProjetoDHZMilhos.Controllers
{
    public class EspecieMilhoController : Controller
    {
        public static List<EspecieMilhoModel> _EspeciesMilho = new List<EspecieMilhoModel>()
        {
            new EspecieMilhoModel()
            {
                ID = 1,
                Nome = "Híbrido SV9298SN",
                Categoria = CategoriaMilho.Doce,
                CorExterna = "Amarelo",
                RendimentoIndustrial = 44,
                UniformidadeColheita = "Alta Uniformidade",
                EstacaoTransplante = "Ano Todo",
                EstacaoPlantio = "Ano Todo",
                EstacaoColheita = "Ano Todo",
                Biotech = true
            }
        };

        public IActionResult Index()
        {
            var model = new EspeciesMilhoModel() { EspeciesMilho = _EspeciesMilho };

            return View(model);
        }

        public IActionResult Record(long id)
        {
            ViewBag.CategoriasMilho = Enum.GetValues(typeof(CategoriaMilho)).Cast<CategoriaMilho>().ToList();
            var especieMilhoAtual = _EspeciesMilho.FirstOrDefault(especieMilho => especieMilho.ID == id);
            return View(especieMilhoAtual);
        }

        [HttpPost]
        public IActionResult Save(EspecieMilhoModel model)
        {
            var especieMilho = _EspeciesMilho.FirstOrDefault(e => e.ID == model.ID);

            especieMilho.Nome = model.Nome;
            especieMilho.Categoria = model.Categoria;
            especieMilho.CorExterna = model.CorExterna;
            especieMilho.RendimentoIndustrial = model.RendimentoIndustrial;
            especieMilho.UniformidadeColheita = model.UniformidadeColheita;
            especieMilho.EstacaoTransplante = model.EstacaoTransplante;
            especieMilho.EstacaoPlantio = model.EstacaoPlantio;
            especieMilho.EstacaoColheita = model.EstacaoColheita;
            especieMilho.Biotech = model.Biotech;

            return RedirectToAction("Index");
        }

        public IActionResult PaginaAdicionar()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Adicionar(EspecieMilhoModel model)
        {
            int idEspecieMilhoNovo = _EspeciesMilho.Count;

            _EspeciesMilho.Add(new EspecieMilhoModel()
            {
                ID = ++idEspecieMilhoNovo,
                Nome = model.Nome,
                Categoria = model.Categoria,
                CorExterna = model.CorExterna,
                RendimentoIndustrial = model.RendimentoIndustrial,
                UniformidadeColheita = model.UniformidadeColheita,
                EstacaoTransplante = model.EstacaoTransplante,
                EstacaoPlantio = model.EstacaoPlantio,
                EstacaoColheita = model.EstacaoColheita,
                Biotech = model.Biotech,
            });

            return RedirectToAction("Index");
        }
    }
}

ProjetoDHZMilhos/Views/EspecieMilho/Index.cshtml
@using ProjetoDHZMilhos.Models.EspecieMilho
@model EspeciesMilhoModel

<div>

    <h1>Espécies Milho</h1>
    <table class="table table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Categoria</th>
                <th>Cor Externa</th>
                <th>Rendimento Industrial</th>
                <th>Uniformidade da Colheita</th>
                <th>Estação de Transplante</th>
                <th>Estação de Plantio</th>
                <th>Estação de Colheita</th>
                <th>Biotech</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var especieMilho in Model.EspeciesMilho)
            {
                <tr>
                    <td>@especieMilho.ID</td>
                    <td>@especieMilho.Nome</td>
                    <td>@especieMilho.Categoria</td>
                    <td>@especieMilho.CorExterna</td>
                    <td>@(especieMilho.RendimentoIndustrial)%</td>
                    <td>@especieMilho.UniformidadeColheita</td>
                    <td>@especieMilho.EstacaoTransplante</td>
                    <td>@especieMilho.EstacaoPlantio</td>
                    <td>@especieMilho.EstacaoColheita</td>
                    <td>@especieMilho.Biotech</td>
                    <td>
                        <a type="button" class="btn btn-info" asp-controller="EspecieMilho" asp-action="Record" asp-route-id="@especieMilho.ID">Editar</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <a type="button" class="btn btn-info float-end" asp-controller="EspecieMilho" asp-action="PaginaAdicionar">Adicionar</a>
</div>

ProjetoDHZMilhos/Views/EspecieMilho/Record.cshtml
@using ProjetoDHZMilhos.Models.EspecieMilho
@model EspecieMilhoModel

<div>
    <h3>Espécie Milho</h3>
    <form asp-controller="EspeciesMilho" asp-action="Save" method="post">
        <input type="hidden" asp-for="ID" />
        <div class="form-group">
            <label>Nome</label>
            <input type="text" id="nome" class="form-control" asp-for="Nome" />
        </div>
        <div class="form-group">
            <label>Categoria do Milho</label>
            @Html.DropDownListFor(
                     model => model.Categoria,
                     new SelectList(ViewBag.CategoriasMilho, "Value", "Text"),
                     "- Selecione -",
                     new { @class = "form-control" }
                     )
        </div>
        <div class="form-group">
            <label>Cor Externa</label>
            <input type="text" id="corExterna" class="form-control" asp-for="CorExterna" />
        </div>
        <div class="form-group">
            <label>Rendimento Industrial</label>
            <input type="number" id="rendmentoIndustrial" class="form-control" asp-for="RendimentoIndustrial" />
        </div>
        <div class="form-group">
            <label>Uniformidade da Colheita</label>
            <input type="text" id="uniformidadeColheita" class="form-control" asp-for="UniformidadeColheita" />
        </div>
        <div class="form-group">
            <label>Estação de Transplante</label>
            <input type="text" id="estacaoTransplante" class="form-control" asp-for="EstacaoTransplante" />
        </div>
        <div class="form-group">
            <label>Estação de Plantio</label>
            <input type="text" id="estacaoPlantio" class="form-control" asp-for="EstacaoPlantio" />
        </div>
        <div class="form-group">
            <label>Estação de Colheita</label>
            <input type="text" id="estacaoColheita" class="form-control" asp-for="EstacaoColheita" />
        </div>
        <div class="form-group">
            <label>Estação de Colheita</label>
            <input type="text" id="estacaoColheita" class="form-control" asp-for="EstacaoColheita" />
        </div>
        <div class="form-group">
            <label>BioTech</label>
            <div>
                <label>@Html.RadioButtonFor(model => model.Biotech, true) Sim </label>
                <label>@Html.RadioButtonFor(model => model.Biotech, false) Não </label>
            </div>
        </div>
        <button type="submit" class="btn btn-primary float-end m-1">Salvar</button>
        <a type="button" class="btn btn-secondary float-end m-1" asp-controller="EspeciesMilho" asp-action="Index">Voltar</a>
    </form>
</div>