ProjetoDHZMilhos/Controllers/ColheitaController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoDHZMilhos.Models.Colheita;


namespace ProjetoDHZMilhos.Controllers
{
    public class ColheitaController : Controller
    {
        public IActionResult Index()
        {
            var colheitas = new List<ColheitaModel>()
            {
                new ColheitaModel(){Id = 1, Data_Colheita = new DateTime(2025, 01, 27), Plantacao_Id = 1, Qualidade = "ÓTIMO", Quantidade_Colhida = 2300000},
                new ColheitaModel(){Id = 2, Data_Colheita = new DateTime(2024, 02, 23), Plantacao_Id = 5, Qualidade = "RUIM", Quantidade_Colhida = 24500000},
                new ColheitaModel(){Id = 1, Data_Colheita = new DateTime(2023, 09, 28), Plantacao_Id = 1, Qualidade = "MEDIANA", Quantidade_Colhida = 2900000},
                new ColheitaModel(){Id = 1, Data_Colheita = new DateTime(2024, 02, 29), Plantacao_Id = 1, Qualidade = "ÓTIMO", Quantidade_Colhida = 3300000}
            };

            var model = new ColheitasModel()
            {
                Colheitas = colheitas
            };

            return View(model);
        }
    }
}

ProjetoDHZMilhos/Controllers/FazendaController.cs
using Microsoft.AspNetCore.Mvc;
using MinhaPrimeiraAplicacao.Utils.Entidades;
using ProjetoDHZMilhos.Models.Fazenda;
using ProjetoDHZMilhos.Models.Plantacao;

namespace ProjetoDHZMilhos.Controllers
{
    public class FazendaController : Controller
    {
        public IActionResult Index()
        {
            var model = new FazendasModel();
            model.Fazendas = new List<FazendaModel>();

            var fazendas = Fazenda.GetAll();

            
            model.Fazendas = fazendas.Select(fazendaEntidade => new FazendaModel(fazendaEntidade)).ToList();

            return View(model);
        }

        public IActionResult Record(long id)
        {
            return View(null);
        }
    }
}

ProjetoDHZMilhos/Controllers/PlantacaoController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoDHZMilhos.Models.Plantacao;

namespace ProjetoDHZMilhos.Controllers
{
    public class PlantacaoController : Controller
    {
        

        public IActionResult Index()
        {
            var plantacoes = new List<PlantacaoModel>()
            {
                new PlantacaoModel() {ID = 1, Fazenda_ID = 1, Nome = "Plantação 1", Area = "10 hectares", Tipo_Milho = "Milho Pipoca"}
            };

            var model = new PlantacoesModel()
            {
                Plantacoes = plantacoes
            };

            return View(model);
        }

        


    }
}

ProjetoDHZMilhos/Controllers/PlantioController.cs
using Microsoft.AspNetCore.Mvc;
using ProjetoDHZMilhos.Models.Plantio;

namespace ProjetoDHZMilhos.Controllers
{
    public class PlantioController : Controller
    {
        public IActionResult Index()
        {

            var plantios = new List<PlantioModel>()
            {
                new PlantioModel()
                {
                    Id = 1,
                    Plantacao_Id = 1,
                    Data_Plantio = new DateTime(2025, 1, 27), 
                    Tipo_Milho = "Milho Pipoca",
                    Quantidade_Sementes = 5000,
                    Hectares_Plantados = 100,
                }
            };

            var model = new PlantiosModel()
            {
                Plantios = plantios
            };

            return View(model);
        }
    }
}

ProjetoDHZMilhos/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ProjetoDHZMilhos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProjetoDHZMilhos.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">CornMeals</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Fazenda" asp-action="Index">Fazenda</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Plantacao" asp-action="Index">Plantação</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Plantio" asp-action="Index">Plantio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Colheita" asp-action="Index">Colheita</a>
                        </li>    
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="EspecieMilho" asp-action="Index">Espécies de Milho</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - CornMeals - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>